// Display-name blocklist. Words are ROT13-encoded so slurs don't sit in the
// source in plain text; `node scripts/names.js list` prints them decoded, and
// `node scripts/names.js check "<name>"` tests a name.
//
//   substring: blocked anywhere in the name once separators are removed
//   token:     blocked only as a whole word (or plural), because they occur
//              inside innocent words ("class", "tycoon", "Essex")
//   allow:     innocent words containing a substring entry ("Gamecocks",
//              "Hancock"); removed before substring matching
//
// Encoded, not secret: this is a readability measure, not security.
export const ENCODED = {
  "substring": [
    "shpx",
    "shx",
    "spx",
    "fuvg",
    "phag",
    "ovgpu",
    "ovngpu",
    "juber",
    "fyhg",
    "avttre",
    "avttn",
    "snttbg",
    "ergneq",
    "encvfg",
    "crqbcuvyr",
    "crqb",
    "anmv",
    "uvgyre",
    "xxx",
    "wvmm",
    "qvpx",
    "pbpx",
    "chffl",
    "cravf",
    "intvan",
    "nffubyr",
    "qhzonff",
    "wnpxnff",
    "fznegnff",
    "onfgneq",
    "cbea",
    "qvyqb",
    "ahgfnpx",
    "fpebghz",
    "grfgvpyr",
    "zvys",
    "betnfz",
    "oybjwbo",
    "unaqwbo",
    "zbyrfg",
    "vaprfg",
    "jrgonpx",
    "enturnq",
    "gbjryurnq",
    "genaal",
    "xvxr",
    "gjng",
    "jnax",
    "obyybpx",
    "pyvg",
    "obare",
    "frzra",
    "nanyfrk",
    "ohggcyht",
    "zbgures",
    "phpx"
  ],
  "token": [
    "nff",
    "snt",
    "encr",
    "fcvp",
    "puvax",
    "tbbx",
    "ornare",
    "qlxr",
    "pbba",
    "phz",
    "gvg",
    "gvgf",
    "obbo",
    "frk",
    "nany",
    "nahf",
    "ubr",
    "arteb",
    "ubaxl",
    "fcnm",
    "ubzb",
    "urvy",
    "anmvf",
    "cvff",
    "penc",
    "fynt",
    "cnxv",
    "wnc",
    "tlc",
    "dhrrs",
    "fxnax",
    "gubg"
  ],
  "allow": [
    "gurencvfg",
    "tnzrpbpx",
    "crnpbpx",
    "unapbpx",
    "jbbqpbpx",
    "onopbpx",
    "uvgpupbpx",
    "pbpxeryy",
    "pbpxgnvy",
    "pbpxcvg",
    "pbpxebnpu",
    "fuhggyrpbpx",
    "qvpxvafba",
    "qvpxraf",
    "qvpxrefba",
    "qvpxrl",
    "fphagubecr",
    "cravfgbar",
    "fuvgnxr",
    "fuvvgnxr",
    "pbpxre",
    "zngfhfuvgn",
    "unapbpxf"
  ]
};

// Impersonation guard (plain text: nothing offensive here).
export const RESERVED_SUBSTRING = ["cfbx"];
export const RESERVED_TOKEN = ["admin", "administrator", "moderator", "mod", "official", "support", "staff", "system", "root", "anonymous", "owner"];
